version: '3'
services:
  kie-server:
    container_name: kie-server
    build:
      context: kie-server
      dockerfile: Dockerfile
    # https://catalog.redhat.com/software/containers/rhpam-7/rhpam-kieserver-rhel8/5db03b6cbed8bd164af2a202
    image: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.12.1-3
    extra_hosts:
      - "kafkahost:${KAFKA_IP}"
    ports:
      - "9080:9080"
    env_file:
      - kie-server.env
  business-central:
    container_name: business-central
    build:
      context: kie-server
      dockerfile: Dockerfile
    # https://catalog.redhat.com/software/containers/rhpam-7/rhpam-businesscentral-rhel8/5db03a9fd70cc516448bdd1e
    image: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.12.1-4
    ports:
      - "9080:8080"
